<a href="https://colab.research.google.com/github/adeleke1508/Ismail_Khaleed_3/blob/main/mnist_neural_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from fastai.vision.all import *

In [7]:
path = untar_data(URLs.MNIST)

In [8]:
path.ls()

(#2) [Path('/root/.fastai/data/mnist_png/training'),Path('/root/.fastai/data/mnist_png/testing')]

In [12]:
train_path= Path(path/'training')
train_path.ls()

(#10) [Path('/root/.fastai/data/mnist_png/training/0'),Path('/root/.fastai/data/mnist_png/training/8'),Path('/root/.fastai/data/mnist_png/training/1'),Path('/root/.fastai/data/mnist_png/training/2'),Path('/root/.fastai/data/mnist_png/training/6'),Path('/root/.fastai/data/mnist_png/training/7'),Path('/root/.fastai/data/mnist_png/training/4'),Path('/root/.fastai/data/mnist_png/training/5'),Path('/root/.fastai/data/mnist_png/training/3'),Path('/root/.fastai/data/mnist_png/training/9')]

In [16]:
zero= (path/'training'/'0').ls().sorted()
one= (path/'training'/'1').ls().sorted()
two= (path/'training'/'2').ls().sorted()
three= (path/'training'/'3').ls().sorted()
four= (path/'training'/'4').ls().sorted()
five= (path/'training'/'5').ls().sorted()
six= (path/'training'/'6').ls().sorted()
seven= (path/'training'/'7').ls().sorted()
eight= (path/'training'/'8').ls().sorted()
nine= (path/'training'/'9').ls().sorted()

In [20]:
train_zero = torch.stack([tensor(Image.open(o)) for o in zero]).float()/255
train_one = torch.stack([tensor(Image.open(o)) for o in one]).float()/255
train_two = torch.stack([tensor(Image.open(o)) for o in two]).float()/255
train_three = torch.stack([tensor(Image.open(o)) for o in three]).float()/255
train_four = torch.stack([tensor(Image.open(o)) for o in four]).float()/255
train_five = torch.stack([tensor(Image.open(o)) for o in five]).float()/255
train_six = torch.stack([tensor(Image.open(o)) for o in six]).float()/255
train_seven = torch.stack([tensor(Image.open(o)) for o in seven]).float()/255
train_eight = torch.stack([tensor(Image.open(o)) for o in eight]).float()/255
train_nine = torch.stack([tensor(Image.open(o)) for o in nine]).float()/255

In [21]:
valid_zero= (path/'testing'/'0').ls().sorted()
valid_one= (path/'testing'/'1').ls().sorted()
valid_two= (path/'testing'/'2').ls().sorted()
valid_three= (path/'testing'/'3').ls().sorted()
valid_four= (path/'testing'/'4').ls().sorted()
valid_five= (path/'testing'/'5').ls().sorted()
valid_six= (path/'testing'/'6').ls().sorted()
valid_seven= (path/'testing'/'7').ls().sorted()
valid_eight= (path/'testing'/'8').ls().sorted()
valid_nine= (path/'testing'/'9').ls().sorted()

In [22]:
test_zero = torch.stack([tensor(Image.open(o)) for o in valid_zero]).float()/255
test_one = torch.stack([tensor(Image.open(o)) for o in valid_one]).float()/255
test_two = torch.stack([tensor(Image.open(o)) for o in valid_two]).float()/255
test_three = torch.stack([tensor(Image.open(o)) for o in valid_three]).float()/255
test_four = torch.stack([tensor(Image.open(o)) for o in valid_four]).float()/255
test_five = torch.stack([tensor(Image.open(o)) for o in valid_five]).float()/255
test_six = torch.stack([tensor(Image.open(o)) for o in valid_six]).float()/255
test_seven = torch.stack([tensor(Image.open(o)) for o in valid_seven]).float()/255
test_eight = torch.stack([tensor(Image.open(o)) for o in valid_eight]).float()/255
test_nine = torch.stack([tensor(Image.open(o)) for o in valid_nine]).float()/255

In [58]:
train_x= torch.cat([train_zero, train_one, train_two, train_three, train_four, train_five, train_six, train_seven, train_eight,train_nine]).view(-1, 28*28)
train_y = tensor([0]*len(zero) + [1]*len(one) + [2]*len(two) + [3]*len(three) + [4]*len(four) + [5]*len(five) +[6]*len(six) + [7]*len(seven) + [8]*len(eight) + [9]*len(nine))#.unsqueeze(1)
train_x.shape, train_y.shape

(torch.Size([60000, 784]), torch.Size([60000]))

In [57]:
valid_x= torch.cat([test_zero, test_one, test_two, test_three, test_four, test_five, test_six, test_seven, test_eight,test_nine]).view(-1, 28*28)
valid_y = tensor([0]*len(valid_zero) + [1]*len(valid_one) + [2]*len(valid_two) + [3]*len(valid_three) + [4]*len(valid_four) + [5]*len(valid_five) +[6]*len(valid_six) + [7]*len(valid_seven) + [8]*len(valid_eight) + [9]*len(valid_nine))#.unsqueeze(1)
valid_x.shape, valid_y.shape

(torch.Size([10000, 784]), torch.Size([10000]))

In [59]:
dset= list(zip(train_x, train_y))
valid_dset=list(zip(valid_x, valid_y))

In [60]:
dl= DataLoader(dset, batch_size=5000)
valid_dl= DataLoader(valid_dset, batch_size=1000)

In [61]:
dls= DataLoaders(dl, valid_dl)

In [62]:
def init_param(size, std=1.0): return (torch.randn(size)*std).requires_grad_()

In [63]:
def mnist_loss(prediction, target):
  criterion = nn.CrossEntropyLoss()
  return criterion(prediction, target)

In [64]:
def batch_accuracy(xb, yb):
  preds=xb.argmax(dim=1)
  correct = (preds==yb)
  return correct.float().mean()

In [65]:
simple_net = nn.Sequential(
    nn.Linear(28*28, 300),
    nn.ReLU(),
    nn.Linear(300, 100),
    nn.ReLU(),
    nn.Linear(100, 10),

)

In [66]:
learn = Learner(dls, simple_net, opt_func=SGD,
                loss_func=mnist_loss,metrics=batch_accuracy, )

In [67]:
learn.fit(40, 0.1)

In [68]:
learn.fit(40, 0.1)

In [69]:
learn.fit(40, 0.1)

In [70]:
learn.fit(40, 0.1)

In [71]:
learn.fit(40, 0.1)

In [72]:
learn.fit(10, 0.1)

In [73]:
learn.fit(20, 0.1)

In [74]:
learn.fit(40, 0.1)

In [75]:
learn.fit(40, 0.1)